twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        category_repo: '@App\Repository\CategoriaRepository'
        products_repo: '@App\Repository\ProductoRepository'
    form_themes: ['bootstrap_4_layout.html.twig']
